apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/group.name: apps
    alb.ingress.kubernetes.io/group.order: "10"

    external-dns.alpha.kubernetes.io/hostname: {{HOSTNAME}}
spec:
  rules:
    - host: {{HOSTNAME}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}
                port:
                  number: 80
